apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy235
  labels:
    app: autodeploy235
  namespace: namespace-workflow-1695625133934
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy235
  template:
    metadata:
      labels:
        app: autodeploy235
    spec:
      containers:
        - name: autodeploy235
          image: acrworkflow1695625133934.azurecr.io/image-workflow-1695625133934:latest
          ports:
            - containerPort: 5000